### ISSUE TITLE
Component not working since last update

### ISSUE THREAD

**Issue by basilebru** [AdaloHQ/map-component#42]
The map component is no longer working.
I get stuck on here.
![Screenshot from 2022-04-29 11-55-41](https://user-images.githubusercontent.com/56433783/166240574-f3b7ec8e-63d3-49b1-8a9d-160e3ae4e1f9.png)

The behaviour is really strange, most input don't work but some do.
Eg:
"48.856613, 2.352222" -> KO
"47.1231231, 2.99999999" -> OK
"Paris, France" -> KO
"Boston" -> OK

It has to do with the latest updates that were made, as the component works fine in my old builds.

Thanks for your help

PS: it's great that you've added latitude, longitude support :) Does it save calls to the geocoding API ?

**Comment by basilebru** [comment]
The problem is the coma: if there is a coma in the address, it is parsed as a latitude / longitude input

**Comment by vkkostin** [comment]
@basilebru Thank you for opening the issue. I believe this should have been fixed with https://github.com/AdaloHQ/map-component/pull/43
